[package]
name = "xtask"
version = "0.1.0"
authors = ["Paul Daniel Faria <Nashenas88@users.noreply.github.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.8"
rs-docker = "0.0.58"

[workspace]
