sudo: false

language: rust

rust:
  - stable
  - beta

script:
  - for dir in coi-test*; do cd $dir; cargo test; cd ..; done

matrix:
  include:
    - rust: nightly
      script:
        - for dir in coi-test*; do cd $dir; cargo test; cd ..; done
        - cargo update -Z minimal-versions && cargo build
