os: linux

language: rust

before_install:
  - rustup component add clippy

rust:
  - stable
  - beta

script:
  - make test EXTRA=--verbose && make clippy EXTRA=--verbose

jobs:
  include:
    - rust: nightly
      script:
        - make test EXTRA=--verbose
        - cargo update -Z minimal-versions && cargo build
  allow_failures:
    - rust: nightly
  fast_finish: true
