[workspace]
members = [
    "coi",
    "coi-actix-sample",
    "coi-actix-web",
    "coi-derive",
    "coi-test",
    "coi-test-debug",
    "coi-test-no-derive",
]

[patch.crates-io]
coi = { path = "coi", version = "0.6.1" }
coi-derive = { path = "coi-derive" }
coi-actix-web = { path = "coi-actix-web" }
