[workspace]
members = [
    "coi",
    "coi-derive",
    "coi-test",
    "coi-test-no-async",
    "coi-test-no-derive",
    "coi-test-no-derive-async"
]

[patch.crates-io]
coi-derive = { path = "coi-derive" }