[workspace]
members = [
    "coi",
    "coi-actix-sample",
    "coi-actix-web",
    "coi-derive",
    "coi-test",
    "coi-test-debug",
    "coi-test-no-derive",
]

[patch.crates-io]
coi-derive = { path = "coi-derive" }