[package]
name = "coi"
version = "0.1.0"
authors = ["Paul Daniel Faria <Nashenas88@users.noreply.github.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Nashenas88/coi"
description = "coi is a Dependency Injection library."
readme = "../README.md"

[dependencies]
async-trait = "0.1.22"
coi-derive = { path = "../coi-derive" }

[patch.crates-io]
coi-derive = { path = "../coi-derive" }
